{
  config,
  lib,
  pkgs,
  ...
}:
with lib; let
  cfg = config.programs.myousync;
in {
  options.programs.myousync = {
    enable = mkEnableOption "Myousync youtube to local files synchronizer";

    package = mkOption {
      type = types.package;
      default = pkgs.myousync;
      defaultText = literalExpression "pkgs.myousync";
      description = "myousync package to use.";
    };

    extraConfig = mkOption {
      default = "";
      example = ''
        foo bar
      '';
      type = types.lines;
      description = ''
        Extra settings for foo.
      '';
    };
  };

  config = mkIf cfg.enable {
    home.packages = [cfg.package];
    xdg.configFile."foo/foorc" = mkIf (cfg.extraConfig != "") {
      text = ''
        # Generated by Home Manager.

        ${cfg.extraConfig}
      '';
    };
  };
}
